www:
  container_name: www_osticket
  image: joffreydupire/osticket:1.0
  ports:
    - "8080:80"
  links:
    - mysql:mysql
  volumes:
    - /www:/var/www/html/

# Database container
mysql:
  container_name: mysql_osticket
  image: mysql:5.7
  env_file:
    - ./mysql_glpi.env
  volumes:
    - /db:/var/lib/mysql
